spring.application.name=garmentfactory
server.port=8082


spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

spring.data.web.pageable.max-page-size=100

# Enable SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# this enables deadlock or circuler dependcy fix this before block 3 ending by splitting service
#done

## Enable statistics to see query counts
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

# Redis connection
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.username=default
# Enable Spring caching
spring.cache.type=redis

# application.properties
# Expose health, info, and metrics endpoints
management.endpoints.web.exposure.include=health,info,metrics
# Show full health details ? which component is up/down, not just overall status
management.endpoint.health.show-details=always
# Enable custom info to show in /actuator/info
management.info.env.enabled=true
# Optional ? give your app identity in /actuator/info
info.app.name=Garment Factory Management System
info.app.description=Backend for garment inventory, orders, and stock management
info.app.version=1.0.0

company.name=Alpha Garment Manufacturing Pvt Ltd
company.address=Plot 12, Industrial Area, Sonepat, Haryana
company.gstin=06ABCDE1234F1Z5
company.gst-rate=0.18
company.signatory-name=Vedansh Vashist
company.signature-image-path=/assets/company-signature.png

