-- V13__create_invoice_tables.sql

CREATE SEQUENCE invoice_number_seq START 1;

CREATE TABLE invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    generated_at TIMESTAMP(6) NOT NULL,

    buyer_name VARCHAR(255) NOT NULL,
    seller_name VARCHAR(255) NOT NULL,
    seller_address VARCHAR(500) NOT NULL,
    seller_gstin VARCHAR(20) NOT NULL,

    subtotal NUMERIC(12,2) NOT NULL,
    gst_rate NUMERIC(4,2) NOT NULL,
    gst_amount NUMERIC(12,2) NOT NULL,
    grand_total NUMERIC(12,2) NOT NULL,

    payment_status VARCHAR(20) NOT NULL,
    signatory_name VARCHAR(255) NOT NULL,

    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),

    created_at TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(6)
);

CREATE TABLE invoice_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoice(id),
    description VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    line_total NUMERIC(12,2) NOT NULL
);