-- Users table
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('OWNER','ADMIN','WORKER','USER')),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT false
);

-- Product table
CREATE TABLE IF NOT EXISTS product (
    pid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garment VARCHAR(255) NOT NULL CHECK (garment IN ('SHIRT','TSHIRT')),
    color VARCHAR(255) NOT NULL CHECK (color IN ('RED','WHITE','BLACK','BLUE','ORANGE')),
    fabric VARCHAR(255) NOT NULL CHECK (fabric IN ('RAYON','COTTON','POLYESTER')),
    cost_per_unit NUMERIC(38,2),
    selling_price NUMERIC(38,2),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (garment, color, fabric)
);

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(255) CHECK (status IN ('ORDERED','PROCESSING','CREATED','DELIVERED','CANCELLED')),
    total_amount NUMERIC(38,2),
    total_cost NUMERIC(38,2),
    total_profit NUMERIC(38,2),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT false
);

-- Stock table
CREATE TABLE IF NOT EXISTS stock (
    sid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    size VARCHAR(255) CHECK (size IN ('SMALL','MEDIUM','LARGE')),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (product_id, size),
    FOREIGN KEY (product_id) REFERENCES product(pid)
);

-- Order Item table
CREATE TABLE IF NOT EXISTS order_item (
    oiid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    p_id BIGINT,
    quantity INTEGER NOT NULL,
    size VARCHAR(255) CHECK (size IN ('SMALL','MEDIUM','LARGE')),
    price_at_purchase NUMERIC(38,2),
    total_amount_of_item NUMERIC(38,2),
    total_cost_of_item NUMERIC(38,2),
    total_profit_of_item NUMERIC(38,2),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (p_id) REFERENCES product(pid)
);